nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:4200']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS']
        expose_headers: ['Link']
        max_age: 3600
        hosts: []
    paths:
        '^/api/':
            allow_origin: ['http://localhost:4200']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS']
